### ISSUE TITLE
Do we really need a var called `grafana` in module `grafana` ? 

### ISSUE THREAD

**Issue by fsismondi** [camptocamp/devops-stack-module-grafana#16]
I have seen we are using this pattern in several modules. 
The module `grafana` has a variable object-like called `grafana`.
I believe this adds a bit of unnecessary complexity on the data types, we simply use flat variables?

**Comment by lentidas** [comment]
Wasn't this already discussed on the weekly? Haven't we said that we would be refactoring this type of catch-all variable to use instead specific variables, like for OIDC?

**Comment by fsismondi** [comment]
I dont recall this discussion. But I was on holiday during the last two meets so maybe I am out of sync. Let's discuss this during next week meet then!
